version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "10000:80"
    volumes:
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
      - ./www/:/var/www/:rw
    networks:
      - net-php

  php:
    image: php:7.0-fpm
    expose:
      - "9000"
    volumes:
      - ./conf/php/php.ini:/etc/php/php.ini:ro
      - ./conf/php/php-fpm.conf:/etc/php/php-fpm.conf:ro
      - ./log/php/:/var/log/php/:rw
      - ./www/:/var/www/:rw
    networks:
      - net-php
      - net-mysql

  mysql:
    image: mysql:5.7    
    container_name: my-mysql
    ports:
      - "10006:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
    networks:
      - net-mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    container_name: my-phpmyadmin
    ports:
      - "10002:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: my-mysql
    networks:
      - net-mysql

networks:
  net-php:
  net-mysql:
